CREATE TABLE Admin (
  idAdmin INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  MailAdmin VARCHAR(100) ,
  MotDePasse VARCHAR(50) ,
  PRIMARY KEY(idAdmin)
)
ENGINE=INNODB;

CREATE TABLE Adresse (
  IdAdresse INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  IdClient INTEGER UNSIGNED NOT NULL ,
  Numero INTEGER UNSIGNED ,
  TypeVoie VARCHAR(15) ,
  Voie VARCHAR(50) ,
  CodePostal INTEGER(5) UNSIGNED ,
  Ville VARCHAR(50) ,
  PRIMARY KEY(IdAdresse, IdClient)
)
ENGINE=INNODB;

CREATE TABLE Article (
  IdArticle INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  RefArticle VARCHAR(30) NOT NULL ,
  DesignationArticle VARCHAR(300) ,
  Prix DOUBLE ,
  Detail TEXT ,
  PRIMARY KEY(IdArticle)
)
ENGINE=INNODB;

CREATE TABLE Categorie (
  idCategorie INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  Nom VARCHAR(50) ,
  PRIMARY KEY(idCategorie)
)
ENGINE=INNODB;

CREATE TABLE Categorie_has_Article (
  idCategorie INTEGER UNSIGNED NOT NULL ,
  IdArticle INTEGER UNSIGNED NOT NULL ,
  PRIMARY KEY(idCategorie, IdArticle)
)
ENGINE=INNODB;

CREATE TABLE Client (
  IdClient INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  Mail VARCHAR(100) NOT NULL ,
  MotDePasse VARCHAR(50) ,
  Nom VARCHAR(35) NOT NULL ,
  Prenom VARCHAR(35) NOT NULL ,
  NumTel VARCHAR(14) NOT NULL ,
  DateNaissance DATE ,
  PRIMARY KEY(IdClient)
)
ENGINE=INNODB;

CREATE TABLE Commande (
  IdCommande INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  idEtat INTEGER UNSIGNED NOT NULL ,
  DateCom DATE ,
  PRIMARY KEY(IdCommande, idEtat)
)
ENGINE=INNODB;

CREATE TABLE Etat (
  idEtat INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  Nom VARCHAR(50) ,
  PRIMARY KEY(idEtat)
)
ENGINE=INNODB;

CREATE TABLE Lignes (
  Commande_IdCommande INTEGER UNSIGNED NOT NULL ,
  IdArticle INTEGER UNSIGNED NOT NULL ,
  IdClient INTEGER UNSIGNED NOT NULL ,
  IdPannier INTEGER UNSIGNED NOT NULL ,
  idEtat INTEGER UNSIGNED NOT NULL ,
  Quantite INTEGER UNSIGNED ,
  PRIMARY KEY(Commande_IdCommande, IdArticle, IdClient, IdPannier, idEtat)
)
ENGINE=INNODB;

CREATE TABLE Panier (
  IdPannier INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  IdClient INTEGER UNSIGNED NOT NULL ,
  PRIMARY KEY(IdPannier, IdClient)
)
ENGINE=INNODB;

CREATE TABLE Support (
  IdMessage INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  IdClient INTEGER UNSIGNED NOT NULL ,
  Titre VARCHAR(100) ,
  PRIMARY KEY(IdMessage, IdClient)
)
ENGINE=INNODB;

CREATE TABLE SupportMessage (
  idSupportMessage INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
  IdClient INTEGER UNSIGNED NOT NULL ,
  IdMessage INTEGER UNSIGNED NOT NULL ,
  Message TEXT ,
  Date DATETIME ,
  PRIMARY KEY(idSupportMessage, IdClient, IdMessage)
)
ENGINE=INNODB;

